# -*- coding: utf-8 -*-
"""yield_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_E3b9V4MBmgfxiiTPvGcjv_Aq3J5axd
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error
from xgboost import XGBRegressor
import numpy as np

df = pd.read_csv("../datasets/crop_production.csv")

df = df.dropna(subset=["Area", "Production"])
df = df[df["Area"] > 0]
df["Yield"] = df["Production"] / df["Area"]

X = df[["State_Name", "District_Name", "Crop_Year", "Season", "Crop", "Area"]]
y = df["Yield"]

categorical = ["State_Name", "District_Name", "Season", "Crop"]
numeric = ["Crop_Year", "Area"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("num", "passthrough", numeric)
    ]
)

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])
